# Generated by Django 5.2.4 on 2025-12-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
