# Generated by Django 5.2.9 on 2025-12-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва розділу')),
            ],
            options={
                'verbose_name': 'Розділ матеріалів',
                'verbose_name_plural': 'Розділи матеріалів',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва матеріалу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('school_class', models.CharField(max_length=20, verbose_name='Клас')),
                ('file', models.FileField(blank=True, help_text='Завантаж PDF / DOCX / ZIP та інші файли', null=True, upload_to='materials/files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='Materials_app.materialcategory', verbose_name='Розділ')),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
                'ordering': ['-created_at'],
            },
        ),
    ]
